### ISSUE TITLE
Language switching doesn't work in the ED

### ISSUE THREAD

**Issue by xfq** [w3c/jlreq#231] opened 2020-08-08 10:57 UTC
After https://github.com/w3c/jlreq/pull/230 is merged, language switching doesn't seem to work in the ED now.

Click 日本語 in https://w3c.github.io/jlreq/ and https://w3c.github.io/jlreq/?specStatus=WG-NOTE&publishDate=2020-08-11&previousPublishDate=2012-04-03&previousMaturity=WG-NOTE and compare the results.

Since this problem is not the first time (see #123), I suggest that we write some tests for this functionality and run them with Travis CI.

/cc @r12a

**Comment by himorin** [comment] 2020-08-09 05:42
hrm,,, it seems working for me, showing only English (for English button) or only Japanese (for 日本語 button)... Could you point specific point(s) I can check?

**Comment by xfq** [comment] 2020-08-09 14:42
The following is a comparison between [ED](https://w3c.github.io/jlreq/) and [WG Note](https://w3c.github.io/jlreq/?specStatus=WG-NOTE&publishDate=2020-08-11&previousPublishDate=2012-04-03&previousMaturity=WG-NOTE) after clicking 日本語 (the result is the same for me in Chrome/Firefox/Safari):

<img width="1476" alt="ED" src="https://user-images.githubusercontent.com/2863444/89734896-710cd180-da91-11ea-9b64-acd41b880886.png">

<img width="1680" alt="NOTE" src="https://user-images.githubusercontent.com/2863444/89734850-402c9c80-da91-11ea-8df5-66e491c3ec17.png">

The reason seems to be that "Previous version" cannot be found in the ED, so an uncaught TypeError is emitted.

**Comment by himorin** [comment] 2020-08-09 16:10
we don't have previousPublishDate in the HEAD yet, so I think this difference is expected behavior.

**Comment by kidayasuo** [comment] 2020-08-10 00:43
What is a right way of testing the function?

**Comment by xfq** [comment] 2020-08-10 01:01
> we don't have previousPublishDate in the HEAD yet, so I think this difference is expected behavior.

That makes sense.

However, we also need to make the code more robust (for example, by handling the exceptions), otherwise when there's a slight change in the ReSpec config or the spec header template, the entire language switching function may not be able to work correctly.

**Comment by xfq** [comment] 2020-08-10 01:08
> What is a right way of testing the function?

Not sure if you mean how to test the behavior in the current ED, or how to write some JavaScript tests for this functionality.

If you mean the former, you can just click 日本語 in https://w3c.github.io/jlreq/ to see the result.

If you mean the latter, I guess we need to use some testing framework with a test runner to run it in a browser (or jsdom).

**Comment by himorin** [comment] 2020-08-10 06:53
> However, we also need to make the code more robust (for example, by handling the exceptions), otherwise when there's a slight change in the ReSpec config or the spec header template, the entire language switching function may not be able to work correctly.

Ah, yes on that point. I wondered whether I've made another mistake for upcoming release (and forgot any other item..).
Considering both easy to be noticed and not to make any change to the production (after compiled/exported by respec), how about 

- to have one additional js block (with class="remove") in index.html for additional test code
- have one wrapper function for switchLang to raise popup by e.g. `try { switchLang() }`
- add code to replace onclick for three buttons, when debug (or something) is added to URL parameter

**Comment by r12a** [comment] 2020-08-10 10:03
I would recommend always testing the switch language functionality by clicking on the buttons (as a user would) before sending a publication request (preferably with the console window open, since there are actually problems associated with the English button, although things appear to work).

@himorin, i think you need to urgently warn the webmaster not to publish until this is fixed, given the time zone differences. Otherwise he may publish while you are sleeping.

**Comment by himorin** [comment] 2020-08-10 12:30
> @himorin, i think you need to urgently warn the webmaster not to publish until this is fixed, given the time zone differences. Otherwise he may publish while you are sleeping.

As noted above, this error is only at github.io ED, since published one has previousPublishDate but ED not. So, no error is detected with the published one.

**Comment by xfq** [comment] 2020-08-10 23:55
> I would recommend always testing the switch language functionality by clicking on the buttons (as a user would) before sending a publication request (preferably with the console window open, since there are actually problems associated with the English button, although things appear to work).

This will help, but it is not enough for people reading ED (unless we publish new versions frequently).

**Comment by himorin** [comment] 2020-09-23 01:57
closing since #234 was merged.

**Closed as completed by himorin** 2020-09-23 01:57 UTC
