### ISSUE TITLE
[simple-ruby] "Treating group ruby as jukugo" seems odd

### ISSUE THREAD

**Issue by r12a** [w3c/jlreq#194] opened 2020-03-25 17:19 UTC
3.3 Placement of group-ruby > BP #5 > NOTE
https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-group-ruby

>  As group-ruby is treated as a unit, there is no wrap opportunity. However, in some exceptional cases where it is wrapped, it is then processed similarly to jukugo-ruby. 

Really??   Isn't it then jukugo-ruby rather than group-ruby, by definition?  It's certainly difficult to know how to implement this without more details surrounding which cases we're talking about.

Perhaps that sentence should either be removed, or changed to say something like: Jukugo-ruby can often look like group-ruby, but allows for text to be wrapped inside the unit.

**Comment by frivoal** [comment] 2020-04-03 10:02
This feels like a duplicate of w3c/simple-ruby#3

**Closed** 2020-04-03 12:38 UTC
Labels: simple-ruby
